apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeai.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "kubeai.selectorLabels" . | nindent 4 }}
